### ISSUE TITLE
Align SaProt with Text?

### ISSUE THREAD

**Issue by Leo-T-Zang** [westlake-repl/ProTrek#3]
Hi ProTrek,

Thanks for sharing this wonderful work!

Quick question: Instead of aligning three Bert models (text, AA, 3Di), why not using text Bert with your previous SaProt model? Wonder if you have tried this approach.

Thanks!

**Comment by LTEnjoy** [comment]
Hi, thank you for your interest in our work!

We didn't align SaProt with text encoder because we want ProTrek to be compatible with  a broad range of applications. SaProt requires both protein sequence and structure to achieve best performance, which limits its retrieval performance in sequence-only or structure-only retrieval tasks. Aligning three modalities provides much more flexibility for users with different needs. Besides, the sequence encoder of ProTrek stills captures structural information since it was pre-trained to align with the structure encoder, so it is not that necessary to adopt SaProt in our ProTrek.

Hope this could resolve your problem :)

**Comment by Leo-T-Zang** [comment]
I see. Awesome. Thanks for explaining!
